WARNING:2023-05-02 16:07:02,160:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:07:02,161:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:08:38,624:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:08:38,624:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:09:23,791:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:09:23,792:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:10:35,889:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:10:35,890:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:11:07,706:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:11:07,706:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:11:37,378:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:11:37,379:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:12:06,391:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:12:06,393:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:14:02,131:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:14:02,132:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:14:59,275:app:start the database connection to create the tracking_id
ERROR:2023-05-02 16:14:59,276:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-02 16:16:17,008:app:start the database connection to create the tracking_id
WARNING:2023-05-02 16:24:19,462:app:start the database connection to create the tracking_id
INFO:2023-05-02 16:24:19,599:app:100's account created
ERROR:2023-05-02 17:20:12,518:settings:Error occurred: name 'set_connection' is not defined
ERROR:2023-05-02 17:20:44,764:settings:Error occurred: name 'set_connection' is not defined
WARNING:2023-05-02 17:22:18,053:app:starting the db connection to display list of tracking_id's
INFO:2023-05-02 17:22:18,574:app:display list of all tracking_id's
WARNING:2023-05-02 17:52:37,454:app:starting the db connection to update the status of tracking_id's
ERROR:2023-05-02 17:52:37,593:settings:Error occurred: column "id" does not exist
LINE 1: SELECT tracking_id from tracking_table where id= 0
                                                     ^

WARNING:2023-05-02 17:52:55,141:app:starting the db connection to update the status of tracking_id's
ERROR:2023-05-02 17:52:55,288:settings:Error occurred: column "id" does not exist
LINE 1: SELECT tracking_id from tracking_table where id= 1
                                                     ^

WARNING:2023-05-02 17:54:51,237:app:starting the db connection to display list of tracking_id's
INFO:2023-05-02 17:54:51,342:app:display list of all tracking_id's
WARNING:2023-05-02 17:54:51,694:app:starting the db connection to display list of tracking_id's
INFO:2023-05-02 17:54:51,785:app:display list of all tracking_id's
WARNING:2023-05-02 17:54:58,428:app:starting the db connection to update the status of tracking_id's
ERROR:2023-05-02 17:54:58,591:settings:Error occurred: column "id" does not exist
LINE 1: SELECT tracking_id from tracking_table where id= 1
                                                     ^

WARNING:2023-05-02 17:57:28,419:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-02 17:57:28,536:app:status updated:{'status': 'shipped'}
WARNING:2023-05-02 17:57:28,537:app:Hence status updated,closing the connection
WARNING:2023-05-02 17:58:07,379:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-02 17:58:07,515:app:status updated:{'status': 'shipped'}
WARNING:2023-05-02 17:58:07,515:app:Hence status updated,closing the connection
WARNING:2023-05-02 17:58:43,192:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-02 17:58:43,319:app:status updated:{'status': 'shipped'}
WARNING:2023-05-02 17:58:43,319:app:Hence status updated,closing the connection
WARNING:2023-05-03 10:08:51,603:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-03 10:08:51,753:settings:Error occurred: syntax error at or near "form"
LINE 1: DELETE form tracking_table WHERE id = 2
               ^

WARNING:2023-05-03 10:09:12,506:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-03 10:09:12,670:settings:Error occurred: column "id" does not exist
LINE 1: DELETE from tracking_table WHERE id = 2
                                         ^

WARNING:2023-05-03 10:09:33,746:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 10:09:33,848:app:tracking_id 2 deleted from the table
WARNING:2023-05-03 10:09:33,849:app:hence the tracking_id is deleted closing the connection
ERROR:2023-05-03 10:32:20,759:settings:Error occurred: 'Logger' object has no attribute 'waring'
WARNING:2023-05-03 10:32:53,620:app:starting data base connection to get report of a particular tracking_id
ERROR:2023-05-03 10:32:53,621:settings:Error occurred: 'int' object does not support indexing
WARNING:2023-05-03 10:35:39,102:app:starting data base connection to get report of a particular tracking_id
ERROR:2023-05-03 10:35:39,103:settings:Error occurred: 'int' object does not support indexing
WARNING:2023-05-03 10:37:08,838:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-03 10:37:08,934:app:generated report of particular id 
WARNING:2023-05-03 10:37:08,934:app:hence we got the report closing the connection
WARNING:2023-05-03 11:24:44,532:app:starting data base connection to create history_id in the table
ERROR:2023-05-03 11:24:44,532:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-03 11:26:32,614:app:starting data base connection to create history_id in the table
ERROR:2023-05-03 11:26:32,774:settings:Error occurred: duplicate key value violates unique constraint "history_table_pkey"
DETAIL:  Key (history_id)=(1) already exists.

WARNING:2023-05-03 11:32:40,191:app:starting data base connection to create history_id in the table
INFO:2023-05-03 11:32:40,309:app:102's history_id created
WARNING:2023-05-03 11:33:09,342:app:starting data base connection to create history_id in the table
ERROR:2023-05-03 11:33:09,344:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 11:33:48,832:app:starting data base connection to create history_id in the table
INFO:2023-05-03 11:33:48,996:app:102's history_id created
WARNING:2023-05-03 11:40:53,830:app:starting the db connection to display list of tracking_id's
INFO:2023-05-03 11:40:53,933:app:display list of all tracking_id's
WARNING:2023-05-03 11:43:25,491:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-03 11:43:25,705:app:status updated:{'status': 'shipping'}
WARNING:2023-05-03 11:43:25,706:app:Hence status updated,closing the connection
WARNING:2023-05-03 11:44:51,966:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 11:44:52,078:app:tracking_id 2 deleted from the table
WARNING:2023-05-03 11:44:52,078:app:hence the tracking_id is deleted closing the connection
WARNING:2023-05-03 11:49:14,235:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 11:49:14,372:app:tracking_id 2 deleted from the table
WARNING:2023-05-03 11:49:14,372:app:hence the tracking_id is deleted closing the connection
WARNING:2023-05-03 11:50:57,554:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 11:50:57,679:app:tracking_id 2 deleted from the table
WARNING:2023-05-03 11:50:57,679:app:hence the tracking_id is deleted closing the connection
WARNING:2023-05-03 11:53:38,881:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 11:53:39,018:app:tracking_id 2 deleted from the table
WARNING:2023-05-03 11:53:39,018:app:hence the tracking_id is deleted closing the connection
WARNING:2023-05-03 11:55:23,281:app:starting the db connection to delete the tracking_id from the table
WARNING:2023-05-03 11:56:32,630:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-03 11:56:32,729:app:generated report of particular id 
WARNING:2023-05-03 11:56:32,729:app:hence we got the report closing the connection
WARNING:2023-05-03 12:09:37,242:app:starting the db connection to display list of history_id's
INFO:2023-05-03 12:09:37,385:app:display list of all history_id's
WARNING:2023-05-03 12:12:46,803:app:starting the db connection to display list of history_id's
INFO:2023-05-03 12:12:46,898:app:display list of all history_id's
WARNING:2023-05-03 12:12:54,384:app:starting data base connection to create history_id in the table
INFO:2023-05-03 12:12:54,478:app:102's history_id created
WARNING:2023-05-03 12:12:59,349:app:starting the db connection to display list of history_id's
INFO:2023-05-03 12:12:59,452:app:display list of all history_id's
WARNING:2023-05-03 12:20:21,343:app:starting data base connection to get report of a particular history_id
INFO:2023-05-03 12:20:21,438:app:generated report of particular id 
WARNING:2023-05-03 12:20:21,438:app:hence we got the report closing the connection
WARNING:2023-05-03 12:28:31,026:app:starting the db connection to delete the tracking_id from the table
INFO:2023-05-03 12:28:31,163:app:history_id 4 deleted from the table
WARNING:2023-05-03 12:28:31,163:app:hence the history_id is deleted closing the connection
WARNING:2023-05-03 12:56:54,775:app:starting data base connection to create return_id in the table
ERROR:2023-05-03 12:56:54,950:settings:Error occurred: insert or update on table "return_table" violates foreign key constraint "return_table_order_id_fkey"
DETAIL:  Key (order_id)=(100) is not present in table "order_table".

WARNING:2023-05-03 13:57:58,574:app:starting the db connection to display list of return_id's
INFO:2023-05-03 13:57:58,695:app:display list of all return_id's
WARNING:2023-05-03 14:04:09,324:app:starting data base connection to get report of a particular return_id
INFO:2023-05-03 14:04:09,435:app:generated report of particular id 
WARNING:2023-05-03 14:04:09,435:app:hence we got the report closing the connection
WARNING:2023-05-03 14:08:51,602:app:starting data base connection to get report of a particular return_id
INFO:2023-05-03 14:08:51,716:app:generated report of particular id 
WARNING:2023-05-03 14:08:51,716:app:hence we got the report closing the connection
WARNING:2023-05-03 14:13:00,062:app:starting data base connection to get report of a particular return_id
ERROR:2023-05-03 14:13:00,063:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:13:10,302:app:starting data base connection to get report of a particular return_id
ERROR:2023-05-03 14:13:10,304:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:13:32,830:app:starting data base connection to get report of a particular return_id
ERROR:2023-05-03 14:13:32,831:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:36:57,811:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:36:57,812:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:37:22,334:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-03 14:37:22,334:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:37:48,958:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:37:48,958:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:41:13,807:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:41:13,808:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:42:17,246:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:42:17,248:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:42:33,630:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:42:33,632:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:56:08,734:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:56:08,734:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 14:58:46,430:app:starting the database connection to delete the return_id
ERROR:2023-05-03 14:58:46,430:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-03 15:06:24,816:app:starting the database connection to delete the return_id
WARNING:2023-05-03 15:06:39,698:app:starting the db connection to update the status of return_id's
WARNING:2023-05-03 15:06:51,326:app:starting the db connection to display list of return_id's
INFO:2023-05-03 15:06:51,452:app:display list of all return_id's
WARNING:2023-05-03 15:12:20,694:app:starting data base connection to create support_id in the table
ERROR:2023-05-03 15:12:20,695:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-03 15:13:30,930:app:starting data base connection to create support_id in the table
ERROR:2023-05-03 15:13:30,931:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-03 15:15:23,860:app:starting data base connection to create support_id in the table
ERROR:2023-05-03 15:15:23,861:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-03 15:20:40,558:app:starting data base connection to create support_id in the table
ERROR:2023-05-03 15:20:40,693:settings:Error occurred: name 'support_id' is not defined
WARNING:2023-05-03 15:22:47,802:app:starting data base connection to create support_id in the table
INFO:2023-05-03 15:22:47,947:app: support_id created
WARNING:2023-05-03 15:25:36,123:app:starting data base connection to create support_id in the table
INFO:2023-05-03 15:25:36,258:app: support_id created
WARNING:2023-05-03 15:27:36,709:app:starting the db connection to display list of support_id's
INFO:2023-05-03 15:27:36,848:app:display list of all support_id's
WARNING:2023-05-03 17:08:11,162:app:starting the db connection to display list of tracking_id's
INFO:2023-05-03 17:08:11,348:app:display list of all tracking_id's
WARNING:2023-05-04 09:24:22,741:app:starting data base connection to create support_id in the table
ERROR:2023-05-04 09:24:22,742:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-04 09:25:26,858:app:starting data base connection to create support_id in the table
ERROR:2023-05-04 09:25:26,858:settings:Error occurred: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
WARNING:2023-05-04 09:26:28,548:app:starting data base connection to create support_id in the table
INFO:2023-05-04 09:26:28,674:app: support_id created
WARNING:2023-05-04 09:26:35,524:app:starting the db connection to display list of support_id's
INFO:2023-05-04 09:26:35,648:app:display list of all support_id's
WARNING:2023-05-04 09:27:31,411:app:starting data base connection to create support_id in the table
INFO:2023-05-04 09:27:31,540:app: support_id created
WARNING:2023-05-04 09:28:23,467:app:starting data base connection to create support_id in the table
INFO:2023-05-04 09:28:23,585:app: support_id created
WARNING:2023-05-04 09:28:32,372:app:starting the db connection to display list of support_id's
INFO:2023-05-04 09:28:32,568:app:display list of all support_id's
WARNING:2023-05-04 09:29:06,840:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-04 09:29:07,016:app:status updated:{'status': 'shipping'}
WARNING:2023-05-04 09:29:07,016:app:Hence status updated,closing the connection
WARNING:2023-05-04 11:20:00,201:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 11:20:00,352:app:generated report of particular id 
WARNING:2023-05-04 11:20:00,352:app:hence we got the report closing the connection
WARNING:2023-05-04 11:23:00,527:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 11:23:00,681:app:generated report of particular id 
WARNING:2023-05-04 11:23:00,682:app:hence we got the report closing the connection
WARNING:2023-05-04 11:25:12,710:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 11:25:12,865:app:generated report of particular id 
WARNING:2023-05-04 11:25:12,866:app:hence we got the report closing the connection
WARNING:2023-05-04 11:25:42,818:app:starting data base connection to get report of a particular history_id
INFO:2023-05-04 11:25:42,966:app:generated report of particular id 
WARNING:2023-05-04 11:25:42,966:app:hence we got the report closing the connection
WARNING:2023-05-04 12:24:35,175:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 12:24:35,343:app:display list of all tracking_id's
WARNING:2023-05-04 12:25:29,643:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-04 12:25:29,790:settings:Error occurred: 'psycopg2.extensions.cursor' object has no attribute 'fetch'
WARNING:2023-05-04 12:25:50,021:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-04 12:25:50,168:settings:Error occurred: name 'tracking_id' is not defined
WARNING:2023-05-04 12:33:03,370:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 12:33:03,528:app:display list of all tracking_id's
WARNING:2023-05-04 12:38:39,020:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 12:38:39,223:app:generated report of particular id 
WARNING:2023-05-04 12:38:39,224:app:hence we got the report closing the connection
WARNING:2023-05-04 12:38:47,718:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-04 12:38:48,025:app:status updated:{'status': 'shipping'}
WARNING:2023-05-04 12:38:48,025:app:Hence status updated,closing the connection
WARNING:2023-05-04 12:40:02,442:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-04 12:40:02,709:app:status updated:{'status': 'shipping'}
WARNING:2023-05-04 12:40:02,710:app:Hence status updated,closing the connection
WARNING:2023-05-04 12:40:13,224:app:starting the db connection to delete the tracking_id from the table
WARNING:2023-05-04 12:45:16,150:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 12:45:16,344:app:generated report of particular id 
WARNING:2023-05-04 12:45:16,344:app:hence we got the report closing the connection
WARNING:2023-05-04 12:49:22,072:app:starting the db connection to display list of history_id's
INFO:2023-05-04 12:49:22,219:app:display list of all history_id's
WARNING:2023-05-04 12:50:35,471:app:starting data base connection to get report of a particular history_id
INFO:2023-05-04 12:50:35,666:app:generated report of particular id 
WARNING:2023-05-04 12:50:35,666:app:hence we got the report closing the connection
WARNING:2023-05-04 12:51:31,096:app:starting data base connection to get report of a particular return_id
WARNING:2023-05-04 12:53:11,660:app:starting the db connection to display list of support_id's
INFO:2023-05-04 12:53:11,926:app:display list of all support_id's
WARNING:2023-05-04 13:00:19,086:app:starting the db connection to display list of history_id's
INFO:2023-05-04 13:00:19,241:app:display list of all history_id's
ERROR:2023-05-04 13:00:19,241:settings:Error occurred: name 'data_list' is not defined
WARNING:2023-05-04 13:00:36,743:app:starting the db connection to display list of history_id's
INFO:2023-05-04 13:00:36,920:app:display list of all history_id's
ERROR:2023-05-04 13:00:36,920:settings:Error occurred: name 'data_list' is not defined
WARNING:2023-05-04 13:00:49,754:app:starting the db connection to display list of history_id's
INFO:2023-05-04 13:00:49,903:app:display list of all history_id's
WARNING:2023-05-04 13:02:31,116:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 13:02:31,353:app:display list of all tracking_id's
WARNING:2023-05-04 13:02:34,651:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 13:02:34,799:app:display list of all tracking_id's
WARNING:2023-05-04 13:03:05,894:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 13:03:06,042:app:display list of all tracking_id's
WARNING:2023-05-04 13:03:33,870:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 13:03:34,010:app:display list of all tracking_id's
WARNING:2023-05-04 14:33:48,462:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 14:33:48,711:app:display list of all tracking_id's
WARNING:2023-05-04 14:34:24,483:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 14:34:24,663:app:display list of all tracking_id's
WARNING:2023-05-04 14:37:57,674:app:starting database connection to get report of refund_id
ERROR:2023-05-04 14:37:58,688:settings:Error occurred: column "transaction_amount" does not exist
LINE 1: SELECT return_id,order_id,refund_amount,transaction_amount,s...
                                                ^

WARNING:2023-05-04 14:38:37,183:app:starting database connection to get report of refund_id
WARNING:2023-05-04 15:25:58,118:app:starting the db connection to display list of tracking_id's
INFO:2023-05-04 15:25:58,309:app:display list of all tracking_id's
WARNING:2023-05-04 15:27:50,076:app:starting the db connection to display list of history_id's
INFO:2023-05-04 15:27:50,244:app:display list of all history_id's
WARNING:2023-05-04 15:28:16,988:app:starting data base connection to get report of a particular history_id
INFO:2023-05-04 15:28:17,287:app:generated report of particular id 
WARNING:2023-05-04 15:28:17,287:app:hence we got the report closing the connection
WARNING:2023-05-04 15:28:41,153:app:starting the db connection to delete the history_id from the table
WARNING:2023-05-04 15:29:04,093:app:starting the db connection to display list of return_id's
INFO:2023-05-04 15:29:04,268:app:display list of all return_id's
WARNING:2023-05-04 15:29:18,773:app:starting data base connection to get report of a particular return_id
WARNING:2023-05-04 15:29:45,257:app:starting the database connection to delete the return_id
WARNING:2023-05-04 15:30:16,942:app:starting the db connection to display list of support_id's
INFO:2023-05-04 15:30:17,288:app:display list of all support_id's
WARNING:2023-05-04 16:26:07,769:app:starting the db connection to update the status of tracking_id's
INFO:2023-05-04 16:26:08,291:app:status updated:{'status': 'shipping'}
WARNING:2023-05-04 16:26:08,292:app:Hence status updated,closing the connection
WARNING:2023-05-04 16:26:26,093:app:starting the db connection to delete the tracking_id from the table
WARNING:2023-05-04 16:26:31,905:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-04 16:26:32,173:app:generated report of particular id 
WARNING:2023-05-04 16:26:32,173:app:hence we got the report closing the connection
WARNING:2023-05-04 16:26:41,146:app:starting data base connection to get report of a particular history_id
INFO:2023-05-04 16:26:41,418:app:generated report of particular id 
WARNING:2023-05-04 16:26:41,418:app:hence we got the report closing the connection
WARNING:2023-05-05 09:51:00,234:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 09:51:00,234:settings:Error occurred: 'NoneType' object has no attribute 'execute'
WARNING:2023-05-05 09:52:42,672:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 09:52:42,672:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 09:56:05,691:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 09:56:05,691:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 09:57:19,666:app:starting data base connection to get report of a particular tracking_id
ERROR:2023-05-05 09:57:19,666:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:00:45,809:app:starting data base connection to get report of a particular tracking_id
ERROR:2023-05-05 10:00:45,810:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:02:12,186:app:starting data base connection to get report of a particular tracking_id
ERROR:2023-05-05 10:02:12,335:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:03:38,096:app:starting data base connection to get report of a particular tracking_id
INFO:2023-05-05 10:03:38,258:app:generated report of particular id 
WARNING:2023-05-05 10:03:38,258:app:hence we got the report closing the connection
WARNING:2023-05-05 10:03:48,999:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 10:03:49,130:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:04:18,722:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 10:04:18,851:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:04:56,032:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 10:04:56,281:settings:Error occurred: update or delete on table "tracking_table" violates foreign key constraint "history_table_tracking_id_fkey" on table "history_table"
DETAIL:  Key (tracking_id)=(3) is still referenced from table "history_table".

WARNING:2023-05-05 10:08:23,962:app:starting the db connection to display list of history_id's
INFO:2023-05-05 10:08:24,210:app:display list of all history_id's
WARNING:2023-05-05 10:08:33,090:app:starting data base connection to get report of a particular history_id
ERROR:2023-05-05 10:08:33,090:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-05 10:12:20,749:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:12:20,926:app:generated report of particular id 
WARNING:2023-05-05 10:12:20,926:app:hence we got the report closing the connection
WARNING:2023-05-05 10:14:51,713:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:14:51,880:app:generated report of particular id 
WARNING:2023-05-05 10:14:51,881:app:hence we got the report closing the connection
WARNING:2023-05-05 10:23:47,214:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:23:47,393:app:generated report of particular id 
WARNING:2023-05-05 10:23:47,393:app:hence we got the report closing the connection
WARNING:2023-05-05 10:24:09,673:app:starting data base connection to get report of a particular history_id
ERROR:2023-05-05 10:24:09,856:settings:Error occurred: cannot unpack non-iterable NoneType object
WARNING:2023-05-05 10:28:48,556:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:28:48,732:app:generated report of particular id 
WARNING:2023-05-05 10:28:48,732:app:hence we got the report closing the connection
WARNING:2023-05-05 10:32:40,142:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:32:40,285:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:36:53,245:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:36:53,392:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:38:09,780:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:38:09,916:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:39:02,977:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:39:03,130:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:41:53,150:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:41:53,299:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:42:52,935:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:42:53,082:settings:Error occurred: list index out of range
WARNING:2023-05-05 10:43:11,146:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:43:11,312:app:generated report of particular id 
WARNING:2023-05-05 10:43:11,313:app:hence we got the report closing the connection
WARNING:2023-05-05 10:47:37,867:app:starting data base connection to get report of a particular history_id
ERROR:2023-05-05 10:47:38,052:settings:Error occurred: name 'keys' is not defined
WARNING:2023-05-05 10:48:11,468:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:48:11,631:app:generated report of particular id 
WARNING:2023-05-05 10:48:11,631:app:hence we got the report closing the connection
WARNING:2023-05-05 10:48:55,433:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:48:55,607:app:generated report of particular id 
WARNING:2023-05-05 10:48:55,607:app:hence we got the report closing the connection
WARNING:2023-05-05 10:49:07,737:app:starting data base connection to get report of a particular history_id
INFO:2023-05-05 10:49:07,906:app:generated report of particular id 
WARNING:2023-05-05 10:49:07,906:app:hence we got the report closing the connection
WARNING:2023-05-05 10:51:16,582:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:51:16,733:settings:Error occurred: not enough values to unpack (expected 7, got 3)
WARNING:2023-05-05 10:52:19,128:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:52:19,278:settings:Error occurred: not enough values to unpack (expected 7, got 3)
WARNING:2023-05-05 10:53:09,277:app:starting the db connection to display list of history_id's
INFO:2023-05-05 10:53:09,492:app:display list of all history_id's
WARNING:2023-05-05 10:54:35,683:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 10:54:35,844:settings:Error occurred: not enough values to unpack (expected 7, got 3)
WARNING:2023-05-05 11:02:04,694:app:starting the db connection to display list of history_id's
INFO:2023-05-05 11:02:04,842:app:display list of all history_id's
WARNING:2023-05-05 11:02:58,137:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 11:02:58,290:settings:Error occurred: not enough values to unpack (expected 7, got 3)
WARNING:2023-05-05 11:03:33,698:app:starting the db connection to display list of history_id's
INFO:2023-05-05 11:03:34,258:app:display list of all history_id's
WARNING:2023-05-05 11:08:41,558:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-05 11:08:41,702:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-05 11:09:08,706:app:starting the db connection to display list of tracking_id's
INFO:2023-05-05 11:09:08,830:app:display list of all tracking_id's
WARNING:2023-05-05 11:09:20,276:app:starting the db connection to display list of tracking_id's
INFO:2023-05-05 11:09:20,399:app:display list of all tracking_id's
WARNING:2023-05-05 11:10:48,988:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-05 11:10:49,117:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-05 11:12:28,729:app:starting the db connection to display list of history_id's
INFO:2023-05-05 11:12:28,862:app:display list of all history_id's
WARNING:2023-05-05 11:12:49,557:app:starting the db connection to display list of history_id's
ERROR:2023-05-05 11:12:49,680:settings:Error occurred: not enough values to unpack (expected 7, got 3)
WARNING:2023-05-05 11:15:14,801:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-05 11:15:14,940:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-05 11:29:54,502:app:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-05 11:29:54,754:settings:Error occurred: update or delete on table "tracking_table" violates foreign key constraint "history_table_tracking_id_fkey" on table "history_table"
DETAIL:  Key (tracking_id)=(3) is still referenced from table "history_table".

WARNING:2023-05-05 11:30:10,303:app:starting the db connection to delete the tracking_id from the table
WARNING:2023-05-05 15:32:27,329:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-05 15:32:27,531:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-05 15:44:19,266:app:starting the db connection to display list of tracking_id's
ERROR:2023-05-05 15:44:19,463:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-06 23:49:07,021:app:start the database connection to create the tracking_id
ERROR:2023-05-06 23:49:07,165:settings:Error occurred: duplicate key value violates unique constraint "tracking_table_pkey"
DETAIL:  Key (tracking_id)=(3) already exists.

WARNING:2023-05-06 23:56:58,818:show all tracking_ids:starting the db connection to display list of tracking_id's
ERROR:2023-05-06 23:56:58,910:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-07 00:00:04,612:show all tracking_ids:starting the db connection to display list of tracking_id's
ERROR:2023-05-07 00:00:04,705:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-07 00:00:20,959:show all tracking_ids:starting the db connection to display list of tracking_id's
ERROR:2023-05-07 00:00:21,049:settings:Error occurred: descriptor 'append' for 'list' objects doesn't apply to a 'dict' object
WARNING:2023-05-07 00:00:44,622:show all tracking_ids:starting the db connection to display list of tracking_id's
INFO:2023-05-07 00:00:44,728:show all tracking_ids:display list of all tracking_id's
WARNING:2023-05-07 00:01:22,853:show all tracking_ids:starting the db connection to display list of tracking_id's
ERROR:2023-05-07 00:01:22,944:settings:Error occurred: not enough values to unpack (expected 5, got 2)
WARNING:2023-05-07 00:04:17,610:show all tracking_ids:starting the db connection to display list of tracking_id's
INFO:2023-05-07 00:04:17,730:show all tracking_ids:display list of all tracking_id's
WARNING:2023-05-07 00:09:26,857:update tracking_id:starting the db connection to update the status of tracking_id's
INFO:2023-05-07 00:09:26,982:update tracking_id:status updated:{'status': 'packing'}
WARNING:2023-05-07 00:09:26,982:update tracking_id:Hence status updated,closing the connection
WARNING:2023-05-07 00:11:27,465:delete tracking_id:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-07 00:11:27,686:settings:Error occurred: update or delete on table "tracking_table" violates foreign key constraint "history_table_tracking_id_fkey" on table "history_table"
DETAIL:  Key (tracking_id)=(3) is still referenced from table "history_table".

WARNING:2023-05-07 00:11:41,259:delete tracking_id:starting the db connection to delete the tracking_id from the table
ERROR:2023-05-07 00:11:41,425:settings:Error occurred: update or delete on table "tracking_table" violates foreign key constraint "history_table_tracking_id_fkey" on table "history_table"
DETAIL:  Key (tracking_id)=(1) is still referenced from table "history_table".

WARNING:2023-05-07 17:12:31,998:report of tracking_id:starting data base connection to get report of a particular tracking_id
INFO:2023-05-07 17:12:32,115:report of tracking_id:generated report of particular id 
WARNING:2023-05-07 17:12:32,115:report of tracking_id:hence we got the report closing the connection
WARNING:2023-05-07 17:27:35,442:create tracking_id:start the database connection to create the tracking_id
INFO:2023-05-07 17:27:35,536:create tracking_id:102's account created
WARNING:2023-05-07 17:28:20,298:show all tracking_ids:starting the db connection to display list of tracking_id's
INFO:2023-05-07 17:28:20,387:show all tracking_ids:display list of all tracking_id's
WARNING:2023-05-07 17:29:08,190:update tracking_id status:starting the db connection to update the status of tracking_id's
INFO:2023-05-07 17:29:08,311:update tracking_id status:status updated:{'status': 'packing'}
WARNING:2023-05-07 17:29:08,311:update tracking_id status:Hence status updated,closing the connection
WARNING:2023-05-07 17:29:39,530:delete tracking_id:starting the db connection to delete the tracking_id from the table
INFO:2023-05-07 17:29:39,656:delete tracking_id:tracking_id 4 deleted from the table
WARNING:2023-05-07 17:29:39,656:delete tracking_id:hence the tracking_id is deleted closing the connection
WARNING:2023-05-07 17:33:36,213:report of tracking_id:starting data base connection to get report of a particular tracking_id
INFO:2023-05-07 17:33:36,327:report of tracking_id:generated report of particular id 
WARNING:2023-05-07 17:33:36,328:report of tracking_id:hence we got the report closing the connection
WARNING:2023-05-07 17:38:25,219:create  history_id:starting data base connection to create history_id in the table
ERROR:2023-05-07 17:38:25,371:settings:Error occurred: insert or update on table "history_table" violates foreign key constraint "history_table_tracking_id_fkey"
DETAIL:  Key (tracking_id)=(5) is not present in table "tracking_table".

WARNING:2023-05-07 17:39:37,501:create tracking_id:start the database connection to create the tracking_id
INFO:2023-05-07 17:39:37,631:create tracking_id:102's account created
WARNING:2023-05-07 17:40:13,845:create  history_id:starting data base connection to create history_id in the table
INFO:2023-05-07 17:40:13,941:create  history_id:12's history_id created
WARNING:2023-05-07 17:42:31,853:show all history_id:starting the db connection to display list of history_id's
ERROR:2023-05-07 17:42:31,963:settings:Error occurred: not enough values to unpack (expected 7, got 4)
WARNING:2023-05-07 17:47:26,786:show all history_id:starting the db connection to display list of history_id's
INFO:2023-05-07 17:47:26,885:show all history_id:display list of all history_id's
ERROR:2023-05-07 17:47:26,886:settings:Error occurred: unsupported operand type(s) for -: 'dict' and 'type'
WARNING:2023-05-07 17:50:23,872:show all history_id:starting the db connection to display list of history_id's
INFO:2023-05-07 17:50:23,963:show all history_id:display list of all history_id's
WARNING:2023-05-07 17:52:02,726:report of history_id:starting data base connection to get report of a particular history_id
INFO:2023-05-07 17:52:02,897:report of history_id:generated report of particular id 
WARNING:2023-05-07 17:52:02,897:report of history_id:hence we got the report closing the connection
WARNING:2023-05-07 17:54:05,129:delete history_id:starting the db connection to delete the history_id from the table
WARNING:2023-05-07 17:59:21,786:create return _id:starting data base connection to create return_id in the table
ERROR:2023-05-07 17:59:21,936:settings:Error occurred: insert or update on table "return_table" violates foreign key constraint "return_table_order_id_fkey"
DETAIL:  Key (order_id)=(12) is not present in table "order_table".

WARNING:2023-05-07 17:59:42,716:create return _id:starting data base connection to create return_id in the table
ERROR:2023-05-07 17:59:42,987:settings:Error occurred: insert or update on table "return_table" violates foreign key constraint "return_table_order_id_fkey"
DETAIL:  Key (order_id)=(102) is not present in table "order_table".

WARNING:2023-05-07 18:09:12,383:show all return_id:starting the db connection to display list of return_id's
WARNING:2023-05-07 18:20:02,932:report of return_id:starting data base connection to get report of a particular return_id
ERROR:2023-05-07 18:20:02,932:settings:Error occurred: can't adapt type 'builtin_function_or_method'
WARNING:2023-05-07 18:30:49,683:report of refund_id:starting database connection to get report of refund_id
WARNING:2023-05-07 18:38:49,710:show all support_id:starting the db connection to display list of support_id's
ERROR:2023-05-07 18:38:49,878:settings:Error occurred: column "suppoert_id" does not exist
LINE 1: select suppoert_id,question,answer from support_table
               ^
HINT:  Perhaps you meant to reference the column "support_table.support_id".

WARNING:2023-05-07 18:39:15,151:show all support_id:starting the db connection to display list of support_id's
INFO:2023-05-07 18:39:15,299:show all support_id:display list of all support_id's
WARNING:2023-05-07 18:41:48,330:show all support_id:starting the db connection to display list of support_id's
INFO:2023-05-07 18:41:48,600:show all support_id:display list of all support_id's
